all:
	gcc -c data.c         -o data
	gcc -c poly.c     	  -o poly
	gcc -c chess.c        -o chess
	gcc -c poker.c 		  -o poker
	gcc hw0501.c poker    -o hw0501
	gcc hw0502.c data     -o hw0502
	gcc hw0503.c poly     -o hw0503
	gcc hw0504.c chess    -o hw0504
